# Generated by Django 5.2.5 on 2026-04-27 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_basis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50)),
                ('province_code', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('seal_path', models.ImageField(blank=True, null=True, upload_to='seals/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('office_code', models.CharField(blank=True, max_length=50)),
                ('office_type', models.CharField(choices=[('department', 'Department'), ('division', 'Division'), ('unit', 'Unit')], max_length=20)),
                ('level_no', models.PositiveIntegerField(default=1)),
                ('office_head', models.CharField(blank=True, max_length=255)),
                ('office_head_title', models.CharField(blank=True, choices=[('DH', 'Department Head'), ('OIC', 'Officer-in-Charge')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.office')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
                'ordering': ['level_no', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('change_description', models.TextField(blank=True)),
                ('legal_basis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal_basis.legalbasis')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='organization.office')),
            ],
            options={
                'verbose_name': 'Office Version',
                'verbose_name_plural': 'Office Versions',
                'ordering': ['-version_no'],
            },
        ),
    ]
