# Generated by Django 5.2.5 on 2026-05-14 07:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_fix_organization_table_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('office_code', models.CharField(blank=True, default='', max_length=100)),
                ('office_type', models.CharField(choices=[('Department', 'Department'), ('Division', 'Division'), ('Unit', 'Unit')], max_length=100)),
                ('level_no', models.PositiveIntegerField(default=1)),
                ('office_head', models.UUIDField(blank=True, null=True)),
                ('office_head_title', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='organization.organization')),
                ('parent_office', models.ForeignKey(blank=True, db_column='parent_office_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.office')),
            ],
            options={
                'db_table': 'organization_office',
                'ordering': ['level_no', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.IntegerField()),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('legal_basis', models.UUIDField()),
                ('change_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('office_id', models.ForeignKey(db_column='office_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='organization.office')),
            ],
            options={
                'db_table': 'organization_office_version',
            },
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(condition=models.Q(('office_code', ''), _negated=True), fields=('organization', 'office_code'), name='uniq_office_code_per_org'),
        ),
    ]
