# Generated by Django 5.2.5 on 2026-05-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_employee_profile_and_officeversion_fks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
    ]
