# Generated by Django 5.2.5 on 2026-04-27 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_basis', '0001_initial'),
        ('organization', '0004_alter_organization_options_office_officeversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('item_number', models.CharField(max_length=50, unique=True)),
                ('position_title', models.CharField(max_length=255)),
                ('salary_grade', models.PositiveIntegerField()),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('casual', 'Casual'), ('contractual', 'Contractual'), ('coterminous', 'Co-terminous')], max_length=20)),
                ('funding_source', models.CharField(choices=[('PS', 'PS'), ('MOOE', 'MOOE'), ('CO', 'CO')], max_length=10)),
                ('position_status', models.CharField(choices=[('filled', 'Filled'), ('vacant', 'Vacant'), ('abolished', 'Abolished')], default='vacant', max_length=20)),
                ('legalbasis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantilla_items', to='legal_basis.legalbasis')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantilla_items', to='organization.office')),
            ],
            options={
                'verbose_name': 'Plantilla Item',
                'verbose_name_plural': 'Plantilla Items',
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('old_salary_grade', models.PositiveIntegerField(blank=True, null=True)),
                ('new_salary_grade', models.PositiveIntegerField(blank=True, null=True)),
                ('change_type', models.CharField(choices=[('salary_grade', 'Salary Grade Change'), ('office', 'Office Reassignment'), ('status', 'Status Change')], max_length=20)),
                ('effective_date', models.DateField()),
                ('legalbasis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal_basis.legalbasis')),
                ('new_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_office_history', to='organization.office')),
                ('old_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_office_history', to='organization.office')),
                ('plantilla_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='plantilla.item')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
                'ordering': ['-effective_date'],
            },
        ),
    ]
