# Generated by Django 5.2.5 on 2026-05-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='employment_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('casual', 'Casual'), ('contractual', 'Contractual'), ('coterminous', 'Job Order/Coterminous')], max_length=20),
        ),
    ]
