# Generated by Django 5.2.5 on 2026-06-01 07:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organization_options'),
        ('plantilla', '0003_item_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='duties_responsibilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='NonPlantillaEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('employee_type', models.CharField(choices=[('JO', 'Job Order'), ('casual', 'Casual')], max_length=20)),
                ('duration_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_unit', models.CharField(choices=[('months', 'Months'), ('years', 'Years')], default='months', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_plantilla_employees', to='organization.office')),
            ],
            options={
                'verbose_name': 'Non-Plantilla Employee',
                'verbose_name_plural': 'Non-Plantilla Employees',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['employee_type'], name='plantilla_n_employe_dfdbc7_idx'), models.Index(fields=['office'], name='plantilla_n_office__634471_idx')],
            },
        ),
    ]
