# Generated by Django 5.2.5 on 2026-06-03 04:20

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0004_item_duties_responsibilities_item_employee_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade_number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salary Grade',
                'verbose_name_plural': 'Salary Grades',
                'db_table': 'salary_grade',
                'ordering': ['grade_number'],
            },
        ),
        migrations.CreateModel(
            name='SalaryGradeStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('amount', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='plantilla.salarygrade')),
            ],
            options={
                'verbose_name': 'Salary Grade Step',
                'verbose_name_plural': 'Salary Grade Steps',
                'db_table': 'salary_grade_step',
                'ordering': ['salary_grade__grade_number', 'step_number'],
                'constraints': [models.UniqueConstraint(fields=('salary_grade', 'step_number'), name='unique_step_per_salary_grade')],
            },
        ),
    ]
