# Generated by Django 5.2.5 on 2026-06-11 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0008_salary_uuid_primary_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salaryschedule',
            constraint=models.UniqueConstraint(fields=('effective_date',), name='unique_salary_schedule_effective_date'),
        ),
    ]
