# Generated by Django 5.2.5 on 2026-06-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0006_appointment_type_expand_non_plantilla'),
        ('plantilla', '0009_salaryschedule_unique_salary_schedule_effective_date'),
    ]

    operations = [
    ]
