# Generated by Django 5.2.5 on 2026-06-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0010_merge_20260615_1447'),
        ('plantilla', '0011_remove_salaryschedule_datetime_fields'),
    ]

    operations = [
    ]
