# Generated by Django 5.2.5 on 2026-06-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0012_merge_20260624_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nonplantillaemployee',
            name='requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nonplantillaemployee',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nonplantillaemployee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
