# Generated by Django 5.2.5 on 2026-04-27 02:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalBasis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reference_type', models.CharField(choices=[('resolution', 'Resolution'), ('EO', 'Executive Order'), ('memo', 'Memorandum'), ('law', 'Republic Act')], max_length=20)),
                ('reference_number', models.CharField(max_length=100)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('effectivity_date', models.DateField()),
                ('document_path', models.FileField(blank=True, null=True, upload_to='legal_basis/')),
            ],
            options={
                'verbose_name': 'Legal Basis',
                'verbose_name_plural': 'Legal Bases',
                'ordering': ['-effectivity_date'],
            },
        ),
    ]
